version: '3.8'

services:

  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    networks:
      - grafana-network
    ports:
      - "3100:3100"
    volumes:
      - "${PWD}:/etc/loki"
    command: -config.file=/etc/loki/loki-config.yml
    restart: unless-stopped

  carnivorous-garden:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carnivorous-garden
    ports: 
      - 5005:5000
    volumes:
      - ./logs:/app/logs/
    networks:
      - grafana-network

  alloy:
    image: grafana/alloy:v1.6.0
    container_name: alloy
    ports:
      - 12345:12345
    volumes:
      - "${PWD}/alloy-config.alloy:/etc/alloy/config.alloy"
      - "${PWD}./logs:/tmp/app-logs/"
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - carnivorous-garden
      - loki
    networks:
      - grafana-network

networks:
  grafana-network:
    external: true # Red ya creada en mi despliegue de Grafana