# Habilita o deshabilita la autenticación en Loki (para este caso, se deja deshabilitada)
auth_enabled: false

limits_config:
  allow_structured_metadata: true
  volume_enabled: true

pattern_ingester:
  enabled: true

server:
  # Puerto donde Loki escuchará las peticiones HTTP
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        # Define el almacenamiento del anillo de ingesta. Aquí se usa memoria en lugar de un almacén distribuido.
        store: inmemory
      replication_factor: 1  # Número de réplicas de los datos en ingesta (1 porque es un entorno simple)
    final_sleep: 0s  # No espera antes de cerrar los ingesters

schema_config:
  configs:
    - from: 2025-02-25  # Fecha de inicio para esta configuración del esquema
      store: tsdb  # Motor de almacenamiento para los logs
      object_store: filesystem  # Usa el sistema de archivos local para almacenar los logs
      schema: v13  # Versión del esquema que se usará
      index:
        prefix: index_  # Prefijo para los índices generados
        period: 24h  # Los índices se rotarán cada 24 horas

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index  # Directorio donde se almacenarán los índices activos
    cache_location: /tmp/loki/index_cache  # Caché de índices
  filesystem:
    directory: /tmp/loki/chunks  # Ubicación donde se almacenarán los chunks de logs en disco

common:
  path_prefix: /tmp/loki
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
    replication_factor: 1

