# Enable or disable authentication in Loki (for this case, it is left disabled)
auth_enabled: false

limits_config:
  allow_structured_metadata: true
  volume_enabled: true

pattern_ingester:
  enabled: true

server:
  # Port where Loki will listen for HTTP requests
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        # Defines the storage of the ingestion ring. Here, memory is used instead of a distributed store.
        store: inmemory
      replication_factor: 1  # Number of replicas of the ingested data (1 because it is a simple environment)
    final_sleep: 0s  # No wait before shutting down the ingesters

schema_config:
  configs:
    - from: 2025-02-25  # Start date for this schema configuration
      store: tsdb  # Storage engine for the logs
      object_store: filesystem  # Uses the local filesystem to store the logs
      schema: v13  # Schema version to be used
      index:
        prefix: index_  # Prefix for the generated indexes
        period: 24h  # Indexes will rotate every 24 hours

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index  # Directory where active indexes will be stored
    cache_location: /tmp/loki/index_cache  # Index cache
  filesystem:
    directory: /tmp/loki/chunks  # Location where log chunks will be stored on disk

common:
  path_prefix: /tmp/loki
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
    replication_factor: 1
